site:
  about:
    siteName: 'sforc'
    subtitle: 'Synths for Compilers'
    siteDescription: 'This is a short blurb you can set below this index layouts sidebar.'
    avatar: '/assets/media/oregonnight.jpg'
  theme: 'FutureImperfect'
  baseUrl: 'netlify'

theme:
  social:
    twitter: '0xLEDev'
    github: 'LorenzoEvans'
    other:
      - label: 'linkedin'
        link: 'https://www.linkedin.com/in/lorev/'
        icon: 'fa-tag'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About'
      itemId: '0xle'
    - type: "pages"
      atRoot: true
    - type: groupPages
      collectionType: pages
      collectionId: allPages
      groups:
        - 'group1'
        - 'group2'
        - 'group3'
        - 'mathematics'
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      template:
        - 'includes/postPreview_list'
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'
  legacySearch: false
  metaComponents:
    - type: orchidSearch

services:
  generators:
    externalIndices:
      - 'https://orchid.run/meta/all.index.json'
