permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'mathematics'
    title: 'Mathematics'
  - key: 'programming'
    title: 'Programming'
  - key: 'systems'
    title: 'Systems'
  - key: 'readinglist'
    title: 'Reading List'
  - key: 'miscellaneous'
    title: 'Miscellaneous'
  - key: 'physics'
    title: 'Physics'

postPages:
  author: '0xle'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
