permalink: ':category/:year/:monthName/:slug'
categories:
  - key: 'mathematics'
    title: 'Mathematics'
  - key: 'physics'
    title: 'Physics'
  - key: 'programming'
    title: 'Programming'

postPages:
  author: '0xle'
  layout: single
  components:
    - type: pageContent
    - type: taxonomy
      taxonomyType: tags
    - type: taxonomy
      taxonomyType: categories
